 # Nombre del workflow
name: CI/CD Backend

# Controla lo que se va a ejecutar (Trigger) pull, push, pull request
on:
    push:
        branches: [main, release, develop]
    pull_request:
        branches: [main, release, develop]

# Pasos a realizar
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Use Node.js 20
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install dependencies
          run: npm ci

        - name: Build NestJS app
          run: npm run build

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ordunamonse/nestjs-api:latest